apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - ../../base

images:
 - name: ghcr.io/mattiaortolani/app-nottambulo-backend
   newName: app-nottambulo-backend
   newTag: local
 - name: ghcr.io/mattiaortolani/app-nottambulo-frontend
   newName: app-nottambulo-frontend
   newTag: local

patches:
 - path: backend-config-patch.yaml
 - path: backend-deployment-patch.yaml
 - path: backend-image-patch.yaml
 - path: frontend-image-patch.yaml
